
version: "3.9"

services:
  db:
    build: ./db
    container_name: mydb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=testdb
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  web:
    build: ./app
    container_name: myflask
    restart: on-failure
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
